"""Job table

Revision ID: 0732c430d1b2
Revises: bb2d3210eb3e
Create Date: 2025-12-01 09:50:38.431295

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0732c430d1b2'
down_revision = 'bb2d3210eb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('datasource_id', sa.Uuid(), nullable=True),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_params', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_datasource_id'), 'job', ['datasource_id'], unique=False)
    op.create_index(op.f('ix_job_job_type'), 'job', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_knowledge_base_id'), 'job', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_index(op.f('ix_job_user_id'), 'job', ['user_id'], unique=False)
    op.create_table('jobevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobevent_job_id'), 'jobevent', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobevent_job_id'), table_name='jobevent')
    op.drop_table('jobevent')
    op.drop_index(op.f('ix_job_user_id'), table_name='job')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_knowledge_base_id'), table_name='job')
    op.drop_index(op.f('ix_job_job_type'), table_name='job')
    op.drop_index(op.f('ix_job_datasource_id'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
