"""s3 path

Revision ID: 1a978b6dc158
Revises: 6d46c4e2dc8d
Create Date: 2025-11-24 08:47:08.248785

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1a978b6dc158'
down_revision = '6d46c4e2dc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasource', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'datasource', 'user', ['owner_id'], ['id'])
    op.add_column('uploadedfile', sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadedfile', 'storage_path')
    op.drop_constraint(None, 'datasource', type_='foreignkey')
    op.drop_column('datasource', 'owner_id')
    # ### end Alembic commands ###
