"""Add persona field

Revision ID: 1d2daf487df6
Revises: 3277621b4924
Create Date: 2025-08-19 11:58:20.942824

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1d2daf487df6'
down_revision = '3277621b4924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('persona', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'persona')
    # ### end Alembic commands ###
