"""remove custom path

Revision ID: 2ea7bac6a845
Revises: f2bd1483d7dd
Create Date: 2025-08-21 07:45:31.676304

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2ea7bac6a845'
down_revision = 'f2bd1483d7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadedfile', 'upload_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadedfile', sa.Column('upload_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
