"""selection_field

Revision ID: 3277621b4924
Revises: 
Create Date: 2025-08-13 15:15:10.559866

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3277621b4924'
down_revision = '0_initial_tables' 
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgebasedatasourcelink', sa.Column('selection', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.drop_column('knowledgebasedatasourcelink', 'files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgebasedatasourcelink', sa.Column('files', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('knowledgebasedatasourcelink', 'selection')
    # ### end Alembic commands ###
