"""fixed chatbot type

Revision ID: 4c06eee31b70
Revises: f90a2d6bd269
Create Date: 2025-11-27 15:20:24.803400

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4c06eee31b70'
down_revision = 'f90a2d6bd269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('datasource_types', sqlmodel.sql.sqltypes.AutoString(), nullable=False,server_default="MOODLE,FILE"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'datasource_types')
    # ### end Alembic commands ###
