"""Enabled field for chatbot

Revision ID: 6d46c4e2dc8d
Revises: 25a9c5c77e21
Create Date: 2025-11-06 15:19:41.275388

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d46c4e2dc8d'
down_revision = '25a9c5c77e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('enabled', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'enabled')
    # ### end Alembic commands ###
