"""Add chatbot Token
Revision ID: 7ef1ca659243
Revises: 2ea7bac6a845
Create Date: 2025-09-22 09:18:31.058428
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '7ef1ca659243'
down_revision = '2ea7bac6a845'
branch_labels = None
depends_on = None

def upgrade():
    op.add_column('chatbot', sa.Column(
        'token',
        sqlmodel.sql.sqltypes.AutoString(),
        nullable=True
    ))

    import uuid
    from sqlalchemy import text

    connection = op.get_bind()

    result = connection.execute(text("SELECT id FROM chatbot WHERE token IS NULL"))
    for row in result:
        token = str(uuid.uuid4()).replace('-', '')
        connection.execute(
            text("UPDATE chatbot SET token = :token WHERE id = :id"),
            {"token": token, "id": row.id}
        )

    op.alter_column('chatbot', 'token', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'token')
    # ### end Alembic commands ###