"""Add Moodle Integration

Revision ID: a83b31c45426
Revises: 7ef1ca659243
Create Date: 2025-09-24 13:28:10.395439

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a83b31c45426'
down_revision = '7ef1ca659243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moodleintegration',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('moodle_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_chatbot_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('moodlecoursechatbotmapping',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('moodle_integration_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chatbot_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.ForeignKeyConstraint(['moodle_integration_id'], ['moodleintegration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('chatbot', 'token')
    op.drop_constraint('moodlecourse_datasource_config_id_moodle_course_id_key', 'moodlecourse', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('moodlecourse_datasource_config_id_moodle_course_id_key', 'moodlecourse', ['datasource_config_id', 'moodle_course_id'])
    op.add_column('chatbot', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('moodlecoursechatbotmapping')
    op.drop_table('moodleintegration')
    # ### end Alembic commands ###
