"""Add password field to chatbot

Revision ID: abc4e2837085
Revises: 1a978b6dc158
Create Date: 2025-11-26 15:49:33.199300

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'abc4e2837085'
down_revision = '1a978b6dc158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'password')
    # ### end Alembic commands ###
