"""enable chatbot by default, and private access level

Revision ID: bb2d3210eb3e
Revises: 4c06eee31b70
Create Date: 2025-11-28 14:07:08.134364

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bb2d3210eb3e'
down_revision = '4c06eee31b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
