"""Add user Role field

Revision ID: d105255ea249
Revises: e9909a40608e
Create Date: 2025-11-06 08:21:50.160774

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd105255ea249'
down_revision = 'e9909a40608e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="user"))
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
