"""Add chatbot owner timestamps

Revision ID: d1267e33596f
Revises: a83b31c45426
Create Date: 2025-10-14 15:35:49.523683

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd1267e33596f'
down_revision = 'a83b31c45426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.add_column('chatbot', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chatbot', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'chatbot', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatbot', type_='foreignkey')
    op.drop_column('chatbot', 'updated_at')
    op.drop_column('chatbot', 'created_at')
    op.drop_column('chatbot', 'owner_id')
    # ### end Alembic commands ###
