"""Rename moodle_id to provider_id


Revision ID: e9909a40608e
Revises: fe66bc588fcd
Create Date: 2025-11-06 08:12:43.601720

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e9909a40608e'
down_revision = 'fe66bc588fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'moodle_id', new_column_name='provider_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'provider_id', new_column_name='moodle_id')
    # ### end Alembic commands ###
