"""Persona Type

Revision ID: f2359fb94ff2
Revises: 0732c430d1b2
Create Date: 2025-12-03 09:18:34.118244

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f2359fb94ff2'
down_revision = '0732c430d1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('personaType', sa.String(), nullable=False, server_default='teacher'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'personaType')
    # ### end Alembic commands ###
