"""access level

Revision ID: f90a2d6bd269
Revises: abc4e2837085
Create Date: 2025-11-26 16:23:35.636843

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f90a2d6bd269'
down_revision = 'abc4e2837085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('access_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='public'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'access_level')
    # ### end Alembic commands ###
